// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: diskjockey-backend/proto/protocol_definitions.proto

// Socket protocol message type IDs used in custom framing (not part of protobuf):
//   2: ReadFileRequest / ReadFileResponse
//   3: WriteFileRequest / WriteFileResponse
// These IDs are used in the daemon's socket protocol to identify message types.

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Central enum for all message type IDs used in the socket protocol
type MessageType int32

const (
	MessageType_UNKNOWN_TYPE        MessageType = 0
	MessageType_LIST_DIR_REQUEST    MessageType = 1
	MessageType_MOUNT_REQUEST       MessageType = 2
	MessageType_UNMOUNT_REQUEST     MessageType = 3
	MessageType_LIST_MOUNTS_REQUEST MessageType = 4
	MessageType_SHUTDOWN_REQUEST    MessageType = 5 // Add other message types as needed
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "LIST_DIR_REQUEST",
		2: "MOUNT_REQUEST",
		3: "UNMOUNT_REQUEST",
		4: "LIST_MOUNTS_REQUEST",
		5: "SHUTDOWN_REQUEST",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN_TYPE":        0,
		"LIST_DIR_REQUEST":    1,
		"MOUNT_REQUEST":       2,
		"UNMOUNT_REQUEST":     3,
		"LIST_MOUNTS_REQUEST": 4,
		"SHUTDOWN_REQUEST":    5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_diskjockey_backend_proto_protocol_definitions_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_diskjockey_backend_proto_protocol_definitions_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{0}
}

// Mount status event (for event-driven updates)
type MountStatus int32

const (
	MountStatus_UNKNOWN   MountStatus = 0
	MountStatus_MOUNTED   MountStatus = 1
	MountStatus_UNMOUNTED MountStatus = 2
	MountStatus_ERROR     MountStatus = 3
)

// Enum value maps for MountStatus.
var (
	MountStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "MOUNTED",
		2: "UNMOUNTED",
		3: "ERROR",
	}
	MountStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"MOUNTED":   1,
		"UNMOUNTED": 2,
		"ERROR":     3,
	}
)

func (x MountStatus) Enum() *MountStatus {
	p := new(MountStatus)
	*p = x
	return p
}

func (x MountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_diskjockey_backend_proto_protocol_definitions_proto_enumTypes[1].Descriptor()
}

func (MountStatus) Type() protoreflect.EnumType {
	return &file_diskjockey_backend_proto_protocol_definitions_proto_enumTypes[1]
}

func (x MountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MountStatus.Descriptor instead.
func (MountStatus) EnumDescriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{1}
}

// Handshake
type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        string                 `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

// List Directory
type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{2}
}

func (x *ListDirRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{3}
}

func (x *ListDirResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListDirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Read File
type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFileRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{5}
}

func (x *ReadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Write File
type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{6}
}

func (x *WriteFileRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{7}
}

func (x *WriteFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Delete File
type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFileRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *DeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Stat (file metadata)
type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{10}
}

func (x *StatRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *FileInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{11}
}

func (x *StatResponse) GetInfo() *FileInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *StatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// List available plugin types
type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{12}
}

type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginTypeInfo      `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{13}
}

func (x *ListPluginsResponse) GetPlugins() []*PluginTypeInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *ListPluginsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PluginTypeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ConfigFields  []*ConfigField         `protobuf:"bytes,3,rep,name=config_fields,json=configFields,proto3" json:"config_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginTypeInfo) Reset() {
	*x = PluginTypeInfo{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginTypeInfo) ProtoMessage() {}

func (x *PluginTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginTypeInfo.ProtoReflect.Descriptor instead.
func (*PluginTypeInfo) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{14}
}

func (x *PluginTypeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginTypeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginTypeInfo) GetConfigFields() []*ConfigField {
	if x != nil {
		return x.ConfigFields
	}
	return nil
}

type ConfigField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigField) Reset() {
	*x = ConfigField{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigField) ProtoMessage() {}

func (x *ConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigField.ProtoReflect.Descriptor instead.
func (*ConfigField) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

// List current mounts
type ListMountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMountsRequest) Reset() {
	*x = ListMountsRequest{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMountsRequest) ProtoMessage() {}

func (x *ListMountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMountsRequest.ProtoReflect.Descriptor instead.
func (*ListMountsRequest) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{16}
}

type ListMountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mounts        []*MountInfo           `protobuf:"bytes,1,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMountsResponse) Reset() {
	*x = ListMountsResponse{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMountsResponse) ProtoMessage() {}

func (x *ListMountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMountsResponse.ProtoReflect.Descriptor instead.
func (*ListMountsResponse) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{17}
}

func (x *ListMountsResponse) GetMounts() []*MountInfo {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *ListMountsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PluginType    string                 `protobuf:"bytes,2,opt,name=plugin_type,json=pluginType,proto3" json:"plugin_type,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountInfo) Reset() {
	*x = MountInfo{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountInfo) ProtoMessage() {}

func (x *MountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountInfo.ProtoReflect.Descriptor instead.
func (*MountInfo) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{18}
}

func (x *MountInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MountInfo) GetPluginType() string {
	if x != nil {
		return x.PluginType
	}
	return ""
}

func (x *MountInfo) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// File metadata
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{19}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

// Mount/Unmount management
type MountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PluginType    string                 `protobuf:"bytes,2,opt,name=plugin_type,json=pluginType,proto3" json:"plugin_type,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountRequest) Reset() {
	*x = MountRequest{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountRequest) ProtoMessage() {}

func (x *MountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountRequest.ProtoReflect.Descriptor instead.
func (*MountRequest) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{20}
}

func (x *MountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MountRequest) GetPluginType() string {
	if x != nil {
		return x.PluginType
	}
	return ""
}

func (x *MountRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type MountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mount         *MountInfo             `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountResponse) Reset() {
	*x = MountResponse{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountResponse) ProtoMessage() {}

func (x *MountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountResponse.ProtoReflect.Descriptor instead.
func (*MountResponse) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{21}
}

func (x *MountResponse) GetMount() *MountInfo {
	if x != nil {
		return x.Mount
	}
	return nil
}

func (x *MountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UnmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountRequest) Reset() {
	*x = UnmountRequest{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountRequest) ProtoMessage() {}

func (x *UnmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountRequest.ProtoReflect.Descriptor instead.
func (*UnmountRequest) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{22}
}

func (x *UnmountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UnmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountResponse) Reset() {
	*x = UnmountResponse{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountResponse) ProtoMessage() {}

func (x *UnmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountResponse.ProtoReflect.Descriptor instead.
func (*UnmountResponse) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{23}
}

func (x *UnmountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Shutdown backend daemon
type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{24}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{25}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShutdownResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MountStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        MountStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=api.MountStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountStatusUpdate) Reset() {
	*x = MountStatusUpdate{}
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountStatusUpdate) ProtoMessage() {}

func (x *MountStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountStatusUpdate.ProtoReflect.Descriptor instead.
func (*MountStatusUpdate) Descriptor() ([]byte, []int) {
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP(), []int{26}
}

func (x *MountStatusUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MountStatusUpdate) GetStatus() MountStatus {
	if x != nil {
		return x.Status
	}
	return MountStatus_UNKNOWN
}

func (x *MountStatusUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_diskjockey_backend_proto_protocol_definitions_proto protoreflect.FileDescriptor

const file_diskjockey_backend_proto_protocol_definitions_proto_rawDesc = "" +
	"\n" +
	"3diskjockey-backend/proto/protocol_definitions.proto\x12\x03api\"*\n" +
	"\x10HandshakeRequest\x12\x16\n" +
	"\x06client\x18\x01 \x01(\tR\x06client\"+\n" +
	"\x11HandshakeResponse\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\"<\n" +
	"\x0eListDirRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"L\n" +
	"\x0fListDirResponse\x12#\n" +
	"\x05files\x18\x01 \x03(\v2\r.api.FileInfoR\x05files\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"=\n" +
	"\x0fReadFileRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"<\n" +
	"\x10ReadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"R\n" +
	"\x10WriteFileRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\")\n" +
	"\x11WriteFileResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"?\n" +
	"\x11DeleteFileRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"*\n" +
	"\x12DeleteFileResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"9\n" +
	"\vStatRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"G\n" +
	"\fStatResponse\x12!\n" +
	"\x04info\x18\x01 \x01(\v2\r.api.FileInfoR\x04info\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x14\n" +
	"\x12ListPluginsRequest\"Z\n" +
	"\x13ListPluginsResponse\x12-\n" +
	"\aplugins\x18\x01 \x03(\v2\x13.api.PluginTypeInfoR\aplugins\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"}\n" +
	"\x0ePluginTypeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x125\n" +
	"\rconfig_fields\x18\x03 \x03(\v2\x10.api.ConfigFieldR\fconfigFields\"s\n" +
	"\vConfigField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\"\x13\n" +
	"\x11ListMountsRequest\"R\n" +
	"\x12ListMountsResponse\x12&\n" +
	"\x06mounts\x18\x01 \x03(\v2\x0e.api.MountInfoR\x06mounts\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xaf\x01\n" +
	"\tMountInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vplugin_type\x18\x02 \x01(\tR\n" +
	"pluginType\x122\n" +
	"\x06config\x18\x03 \x03(\v2\x1a.api.MountInfo.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\"\xb5\x01\n" +
	"\fMountRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vplugin_type\x18\x02 \x01(\tR\n" +
	"pluginType\x125\n" +
	"\x06config\x18\x03 \x03(\v2\x1d.api.MountRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\rMountResponse\x12$\n" +
	"\x05mount\x18\x01 \x01(\v2\x0e.api.MountInfoR\x05mount\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"$\n" +
	"\x0eUnmountRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\x0fUnmountResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x11\n" +
	"\x0fShutdownRequest\"F\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\x11MountStatusUpdate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.api.MountStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*\x8c\x01\n" +
	"\vMessageType\x12\x10\n" +
	"\fUNKNOWN_TYPE\x10\x00\x12\x14\n" +
	"\x10LIST_DIR_REQUEST\x10\x01\x12\x11\n" +
	"\rMOUNT_REQUEST\x10\x02\x12\x13\n" +
	"\x0fUNMOUNT_REQUEST\x10\x03\x12\x17\n" +
	"\x13LIST_MOUNTS_REQUEST\x10\x04\x12\x14\n" +
	"\x10SHUTDOWN_REQUEST\x10\x05*A\n" +
	"\vMountStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aMOUNTED\x10\x01\x12\r\n" +
	"\tUNMOUNTED\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03B\"Z diskjockey-backend/proto/api;apib\x06proto3"

var (
	file_diskjockey_backend_proto_protocol_definitions_proto_rawDescOnce sync.Once
	file_diskjockey_backend_proto_protocol_definitions_proto_rawDescData []byte
)

func file_diskjockey_backend_proto_protocol_definitions_proto_rawDescGZIP() []byte {
	file_diskjockey_backend_proto_protocol_definitions_proto_rawDescOnce.Do(func() {
		file_diskjockey_backend_proto_protocol_definitions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diskjockey_backend_proto_protocol_definitions_proto_rawDesc), len(file_diskjockey_backend_proto_protocol_definitions_proto_rawDesc)))
	})
	return file_diskjockey_backend_proto_protocol_definitions_proto_rawDescData
}

var file_diskjockey_backend_proto_protocol_definitions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_diskjockey_backend_proto_protocol_definitions_proto_goTypes = []any{
	(MessageType)(0),            // 0: api.MessageType
	(MountStatus)(0),            // 1: api.MountStatus
	(*HandshakeRequest)(nil),    // 2: api.HandshakeRequest
	(*HandshakeResponse)(nil),   // 3: api.HandshakeResponse
	(*ListDirRequest)(nil),      // 4: api.ListDirRequest
	(*ListDirResponse)(nil),     // 5: api.ListDirResponse
	(*ReadFileRequest)(nil),     // 6: api.ReadFileRequest
	(*ReadFileResponse)(nil),    // 7: api.ReadFileResponse
	(*WriteFileRequest)(nil),    // 8: api.WriteFileRequest
	(*WriteFileResponse)(nil),   // 9: api.WriteFileResponse
	(*DeleteFileRequest)(nil),   // 10: api.DeleteFileRequest
	(*DeleteFileResponse)(nil),  // 11: api.DeleteFileResponse
	(*StatRequest)(nil),         // 12: api.StatRequest
	(*StatResponse)(nil),        // 13: api.StatResponse
	(*ListPluginsRequest)(nil),  // 14: api.ListPluginsRequest
	(*ListPluginsResponse)(nil), // 15: api.ListPluginsResponse
	(*PluginTypeInfo)(nil),      // 16: api.PluginTypeInfo
	(*ConfigField)(nil),         // 17: api.ConfigField
	(*ListMountsRequest)(nil),   // 18: api.ListMountsRequest
	(*ListMountsResponse)(nil),  // 19: api.ListMountsResponse
	(*MountInfo)(nil),           // 20: api.MountInfo
	(*FileInfo)(nil),            // 21: api.FileInfo
	(*MountRequest)(nil),        // 22: api.MountRequest
	(*MountResponse)(nil),       // 23: api.MountResponse
	(*UnmountRequest)(nil),      // 24: api.UnmountRequest
	(*UnmountResponse)(nil),     // 25: api.UnmountResponse
	(*ShutdownRequest)(nil),     // 26: api.ShutdownRequest
	(*ShutdownResponse)(nil),    // 27: api.ShutdownResponse
	(*MountStatusUpdate)(nil),   // 28: api.MountStatusUpdate
	nil,                         // 29: api.MountInfo.ConfigEntry
	nil,                         // 30: api.MountRequest.ConfigEntry
}
var file_diskjockey_backend_proto_protocol_definitions_proto_depIdxs = []int32{
	21, // 0: api.ListDirResponse.files:type_name -> api.FileInfo
	21, // 1: api.StatResponse.info:type_name -> api.FileInfo
	16, // 2: api.ListPluginsResponse.plugins:type_name -> api.PluginTypeInfo
	17, // 3: api.PluginTypeInfo.config_fields:type_name -> api.ConfigField
	20, // 4: api.ListMountsResponse.mounts:type_name -> api.MountInfo
	29, // 5: api.MountInfo.config:type_name -> api.MountInfo.ConfigEntry
	30, // 6: api.MountRequest.config:type_name -> api.MountRequest.ConfigEntry
	20, // 7: api.MountResponse.mount:type_name -> api.MountInfo
	1,  // 8: api.MountStatusUpdate.status:type_name -> api.MountStatus
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_diskjockey_backend_proto_protocol_definitions_proto_init() }
func file_diskjockey_backend_proto_protocol_definitions_proto_init() {
	if File_diskjockey_backend_proto_protocol_definitions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diskjockey_backend_proto_protocol_definitions_proto_rawDesc), len(file_diskjockey_backend_proto_protocol_definitions_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_diskjockey_backend_proto_protocol_definitions_proto_goTypes,
		DependencyIndexes: file_diskjockey_backend_proto_protocol_definitions_proto_depIdxs,
		EnumInfos:         file_diskjockey_backend_proto_protocol_definitions_proto_enumTypes,
		MessageInfos:      file_diskjockey_backend_proto_protocol_definitions_proto_msgTypes,
	}.Build()
	File_diskjockey_backend_proto_protocol_definitions_proto = out.File
	file_diskjockey_backend_proto_protocol_definitions_proto_goTypes = nil
	file_diskjockey_backend_proto_protocol_definitions_proto_depIdxs = nil
}
